### ISSUE TITLE
When will the code and dataset be available?

### ISSUE THREAD

**Issue by fanzfan** [ShanghaiTech-IMPACT/CeLDA#1]
Hi, I am interested in your work and would like to reproduce the results asap.

**Comment by Fitz-Fitz** [comment]
Hi Fan, thank you for your interest in our work.  We expect to release the dataset along with the source code by the end of Aug.

**Comment by Fitz-Fitz** [comment]
Hi Fan, the source code has been released. Dataset on its way (it may take a while).

**Comment by Fitz-Fitz** [comment]
Hi Fan, dataset is now released.
